#!/usr/bin/env python3
"""The packaged canonical skill taxonomy ("skill cloud").

Loads ``jobjob/data/skill_cloud.toml`` (generated by
``scripts/curate_skill_cloud.py`` from an ESCO release; see the file header and
``jobjob/data/NOTICE-ESCO.md`` for provenance and attribution) and provides
case-insensitive canonical resolution by name, alias, or id.

Resolution precedence: exact id, then name, then alias. Lookup failures return
``None`` -- callers decide whether that means UNMAPPED (JD requirements) or
non-canonical (user skills); the cloud never guesses a near match.
"""

import dataclasses as dcs
import logging
import tomllib
from functools import lru_cache
from pathlib import Path
from typing import Optional

LOGGER = logging.getLogger(__name__)

# __file__-relative so the packaged data resolves the same from a checkout and an
# installed wheel (hatchling bundles the whole jobjob/ tree).
_DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "skill_cloud.toml"
_WEIGHT_SUM_TOLERANCE = 0.01

CATEGORIES = (
    "communication",
    "collaboration",
    "leadership",
    "creativity",
    "technical",
    "domain",
)


# Errors
# ======================================================================


class SkillCloudError(ValueError):
    """Raise if the skill cloud data fails validation."""


# Structures
# ======================================================================


@dcs.dataclass(frozen=True)
class CloudSkill:
    """A canonical skill.

    Attributes:
        id: Stable canonical identifier (snake_case).
        name: Display name.
        aliases: Alternative labels used for resolution.
        categories: Weighted category membership; weights sum to 1.0.
        esco_uri: Source ESCO concept URI (provenance).
    """

    id: str
    name: str
    aliases: tuple[str, ...]
    categories: dict[str, float]
    esco_uri: str = ""


@dcs.dataclass(frozen=True)
class SkillCloud:
    """The loaded taxonomy plus its lookup index.

    Attributes:
        skills: Canonical skills keyed by id.
        esco_version: Source ESCO release recorded in the data file.
        _index: Lowercased name/alias/id -> canonical id.
    """

    skills: dict[str, CloudSkill]
    esco_version: str
    _index: dict[str, str]

    def resolve(self, text: str) -> Optional[CloudSkill]:
        """Resolve free text to a canonical skill (case-insensitive).

        Precedence: id, then name, then alias (already encoded in the index).

        Arguments:
            text: A skill label, alias, or id.
        Returns:
            The canonical skill, or None if nothing matches exactly.
        """
        if not text:
            return None
        canonical_id = self._index.get(text.strip().lower())
        return self.skills.get(canonical_id) if canonical_id else None

    def __len__(self) -> int:
        return len(self.skills)


# Loading
# ======================================================================


def _validate_entry(raw: dict) -> CloudSkill:
    entry_id = raw.get("id")
    name = raw.get("name")
    categories = raw.get("categories", {})
    if not entry_id or not name:
        raise SkillCloudError(f"Cloud entry missing id or name: {raw!r}")
    unknown = set(categories) - set(CATEGORIES)
    if unknown:
        raise SkillCloudError(f"Unknown categories {sorted(unknown)} in '{entry_id}'")
    total = sum(categories.values())
    if abs(total - 1.0) > _WEIGHT_SUM_TOLERANCE:
        raise SkillCloudError(
            f"Category weights for '{entry_id}' sum to {total:.3f}, expected 1.0"
        )
    return CloudSkill(
        id=entry_id,
        name=name,
        aliases=tuple(raw.get("aliases", [])),
        categories=dict(categories),
        esco_uri=raw.get("esco_uri", ""),
    )


def _build(data: dict) -> SkillCloud:
    cloud_meta = data.get("cloud", {})
    raw_skills = cloud_meta.get("skill", [])
    skills: dict[str, CloudSkill] = {}
    index: dict[str, str] = {}

    for raw in raw_skills:
        skill = _validate_entry(raw)
        if skill.id in skills:
            raise SkillCloudError(f"Duplicate canonical id: '{skill.id}'")
        skills[skill.id] = skill

    # Index in precedence order: id > name > alias. Later writes must not
    # overwrite earlier (higher-precedence) ones, so ids first, aliases last.
    for skill in skills.values():
        index.setdefault(skill.id.lower(), skill.id)
    for skill in skills.values():
        index.setdefault(skill.name.lower(), skill.id)
    for skill in skills.values():
        for alias in skill.aliases:
            index.setdefault(alias.lower(), skill.id)

    return SkillCloud(
        skills=skills,
        esco_version=str(cloud_meta.get("esco_version", "")),
        _index=index,
    )


def load_skill_cloud(path: Optional[Path] = None) -> SkillCloud:
    """Load and validate a skill cloud.

    Arguments:
        path: Explicit TOML path (tests); defaults to the packaged data file.
    Returns:
        The validated SkillCloud.
    Raises:
        SkillCloudError(ValueError) on any validation failure.
        FileNotFoundError if an explicit path does not exist.
    """
    data_path = Path(path).expanduser().resolve() if path is not None else _DATA_PATH
    content = data_path.read_bytes()
    return _build(tomllib.loads(content.decode("utf-8")))


@lru_cache(maxsize=1)
def get_skill_cloud() -> SkillCloud:
    """Return the packaged skill cloud (cached)."""
    return load_skill_cloud()


# Normalization
# ======================================================================


@dcs.dataclass(frozen=True)
class NormalizedRequirement:
    """A JD requirement resolved against the skill cloud.

    Attributes:
        text: The original JD phrasing (always preserved).
        canonical_id: The resolved canonical skill id, or None when UNMAPPED.
        categories: The canonical skill's category weights ({} when UNMAPPED).
    """

    text: str
    canonical_id: Optional[str] = None
    categories: dict[str, float] = dcs.field(default_factory=dict)

    @property
    def unmapped(self) -> bool:
        return self.canonical_id is None


def normalize_requirements(
    requirements: "list[str] | tuple[str, ...]",
    proposals: Optional[dict] = None,
    cloud: Optional[SkillCloud] = None,
) -> tuple[NormalizedRequirement, ...]:
    """Resolve JD requirement strings to canonical skills.

    Resolution is exact-match only (model proposal first, then the literal JD
    phrasing); anything else stays UNMAPPED with its original text — a gap or a
    taxonomy hole is surfaced, never bridged to a near match.

    Arguments:
        requirements: JD requirement/skill strings (original phrasing).
        proposals: Model-proposed canonical names keyed by requirement text
            (``JobDescription.canonical_skills``); may be None/empty for older
            cached parses.
        cloud: The skill cloud (defaults to the packaged cloud).
    Returns:
        One NormalizedRequirement per input, in order.
    """
    cloud = cloud if cloud is not None else get_skill_cloud()
    proposals = dict(proposals) if proposals else {}
    results = []
    for text in requirements:
        if not text:
            continue
        skill = cloud.resolve(proposals.get(text, "")) or cloud.resolve(text)
        if skill is None:
            results.append(NormalizedRequirement(text=text))
        else:
            results.append(
                NormalizedRequirement(
                    text=text,
                    canonical_id=skill.id,
                    categories=dict(skill.categories),
                )
            )
    return tuple(results)


# __END__
